[versions]
androidGradlePlugin = "9.4.1"

androidxAppcompat = "1.8.0"
androidxCore = "1.19.1"
androidxWebkit = "1.17.1"
junit = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }
junit = { module = "junit:junit", version.ref = "junit" }
